# Generated by Django 6.0.7 on 2026-08-10 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0004_alter_review_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_type',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
    ]
